# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

# Theme
theme = ["blowfish"]

baseURL = "https://lfgberg.org/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

timeout = 180000
buildDrafts = false
buildFuture = false

googleAnalytics = "G-80P7KGTQ64"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
