# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["projects", "posts", "photo"]
# robots = ""

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  showRecent = true
  showRecentItems = 15
  showMoreLink = false
  showMoreLinkDest = "/posts"
  homepageImage = "homepage.jpg"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true


[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  sharingLinks = false

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  cardView = false
  groupByYear = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  apiKey = "AIzaSyCo2aGTMQjIMxbAa9Xy3nWHmdQxxwxaU98"
  # authDomain = "hugo-portfolio-site.firebaseapp.com"
  # projectId = "hugo-portfolio-site"
  # storageBucket = "hugo-portfolio-site.appspot.com"
  # messagingSenderId = "209448175700"
  # appId = "1:209448175700:web:088004d90283d7d90785c1"
  # measurementId = "G-1S9JC45ZKT"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
   identifier = "lfgberg"
   globalWidget = true
  # globalWidgetMessage = "Hello"
   globalWidgetColor = "#3b82f6"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
